# Generated by Django 3.2.7 on 2021-09-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="total_like",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
