# Generated by Django 3.2.7 on 2021-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_total_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="total_like",
            new_name="total_likes",
        ),
    ]
